import { useEffect, useRef } from 'react'
import { Platform } from 'react-native'
import Constants from 'expo-constants'

// Enable mqtt.js debug logging if configured
if (process.env.EXPO_PUBLIC_MQTT_DEBUG === 'true') {
  // @ts-ignore - debug is internal to mqtt
  if (typeof global !== 'undefined') {
    // @ts-ignore
    global.localStorage = global.localStorage || {
      debug: 'mqttjs*',
      getItem: (key: string) => (key === 'debug' ? 'mqttjs*' : null),
      setItem: () => {},
      removeItem: () => {}
    }
  }
}

import mqtt from 'mqtt'
import { ConsumerBase } from '@tetherto/qvac-test-suite/mobile'
import type { IClientOptions, MqttClient } from 'mqtt'
import { executor } from './executor'
import { config as consumerConfig } from './consumer-config'

// react-native-performance-toolkit is loaded lazily so the consumer still
// works on builds that haven't installed the optional dependency.
let getMemoryUsage: (() => number) | undefined
let getIosTaskVmInfo:
  | (() => {
      physFootprintMb?: number
      regionCount?: number
      residentSizeKb?: number
    })
  | undefined
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const performanceToolkit = require('react-native-performance-toolkit')
  getMemoryUsage = performanceToolkit.getMemoryUsage

  const performanceToolkitHybrid = performanceToolkit.PerformanceToolkit
  const memoryBufferGetter = performanceToolkitHybrid?.getMemoryUsageBuffer
  if (typeof memoryBufferGetter === 'function') {
    // Buffer layout (little-endian), as produced by the QVAC patch to the
    // native toolkit (see patchPerformanceToolkitIosMemoryBuffer):
    //   offset  0 : int32   phys_footprint (MB)    -- primary, jetsam-relevant
    //   offset  8 : float64 resident_size  (KB)    -- resident secondary
    //   offset 16 : float64 region_count   (count) -- address-space diagnostic
    // virtual_size is intentionally not produced (useless as a usage signal).
    getIosTaskVmInfo = () => {
      const buffer = performanceToolkitHybrid.getMemoryUsageBuffer()
      if (!buffer) return {}
      const view = new DataView(buffer)
      const physFootprintMb = view.byteLength >= 4 ? view.getInt32(0, true) : undefined
      return {
        physFootprintMb,
        residentSizeKb: view.byteLength >= 16 ? view.getFloat64(8, true) : undefined,
        regionCount: view.byteLength >= 24 ? view.getFloat64(16, true) : undefined
      }
    }
  }
} catch {
  // toolkit not installed; in-app memory publishing will be skipped.
}

type MemoryUnit = 'kb' | 'count'

interface MemoryWindowSample {
  value: number
  ts: number
  unit: MemoryUnit
}

function isPositiveFiniteNumber(value: unknown): value is number {
  return typeof value === 'number' && isFinite(value) && value > 0
}

// RPC command id for memory samples pushed from the /proc sampling worklet.
// Must match RPC_MEM_SAMPLE in proc-mem-worklet.mjs.
const RPC_MEM_SAMPLE = 1

// Bare worklet bits for the Android /proc memory sampler. All optional: any
// missing piece (toolkit not installed, bundle not generated by the build,
// non-Android platform) simply skips the extra series without affecting the
// existing in-app poller.
let Worklet: any
let BareRPC: any
let procMemBundle: any
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  Worklet = require('react-native-bare-kit').Worklet
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  BareRPC = require('bare-rpc').default || require('bare-rpc')
  // Generated at mobile-build time by `bare-pack`. The build always writes at
  // least a stub (`export default null`) so this require resolves.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  procMemBundle = require('./proc-mem-worklet.bundle.mjs').default
} catch {
  // Bare worklet sampling unavailable; only the in-app poller will run.
}

// Decode an RPC payload (Buffer / Uint8Array / string) to a UTF-8 string.
function decodeRpcData(data: unknown): string {
  if (typeof data === 'string') return data
  const anyData = data as any
  if (anyData && typeof global !== 'undefined' && (global as any).Buffer?.isBuffer?.(anyData)) {
    return anyData.toString('utf8')
  }
  if (typeof TextDecoder !== 'undefined' && anyData) {
    try {
      return new TextDecoder().decode(anyData)
    } catch {
      // fall through
    }
  }
  if (anyData && typeof anyData.length === 'number') {
    let s = ''
    for (let i = 0; i < anyData.length; i++) s += String.fromCharCode(anyData[i])
    return s
  }
  return ''
}

// Optional bootstrap hook — may or may not be exported by the user's executor module
let bootstrap: (() => Promise<void>) | undefined
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const executorModule = require('./executor')
  if (typeof executorModule.bootstrap === 'function') {
    bootstrap = executorModule.bootstrap
  }
} catch {
  // bootstrap not available
}

// Optional test definitions — required for consumer-side test resolution
let testDefinitions: any[] | undefined
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const testDefsModule = require('./test-definitions')
  testDefinitions = testDefsModule.tests || testDefsModule.default
} catch {
  // test definitions not bundled — consumer will fail on queued test resolution
}

interface ConsumerWrapperProps {
  log: (message: string) => void
  updateStats: (stats: {
    testsCompleted?: number
    testsPassed?: number
    testsFailed?: number
    totalTests?: number
    currentTest?: string
    isComplete?: boolean
  }) => void
}

export function ConsumerWrapper({ log, updateStats }: ConsumerWrapperProps) {
  const consumerRef = useRef<ConsumerBase | null>(null)

  useEffect(() => {
    let client: MqttClient | null = null
    let isInitialized = false
    let isShuttingDown = false
    let memMeasureHandle: ReturnType<typeof setInterval> | undefined
    let memReportHandle: ReturnType<typeof setInterval> | undefined
    let procMemWorklet: any
    const stopProcMemWorklet = () => {
      if (procMemWorklet) {
        try {
          procMemWorklet.terminate()
        } catch {
          // already gone
        }
        procMemWorklet = undefined
      }
    }

    // lunte-disable-next-line require-await
    ;(async () => {
      if (isInitialized) return
      isInitialized = true

      try {
        // MQTT.js debug logging can be enabled by uncommenting:
        // const debug = require('debug');
        // debug.log = console.log.bind(console);
        // debug.enable('mqtt*,mqttjs*,mqtt-packet*');

        // Read config (baked at build time)
        const { mqtt: mqttConfig, runId } = consumerConfig

        log('🔧 Initializing consumer...')
        log(`📱 Device: ${Constants.deviceName || 'Unknown'} | Run ID: ${runId}`)
        log(
          `📡 Connecting to ${mqttConfig.protocol}://${mqttConfig.host}:${mqttConfig.port}${mqttConfig.path}`
        )

        // Build broker URL with path for WebSocket
        const brokerUrl = `${mqttConfig.protocol}://${mqttConfig.host}:${mqttConfig.port}${mqttConfig.path}`

        const consumerPlatform = `mobile-${Platform.OS}`
        // Generate consumer ID early so we can use it as MQTT clientId
        const consumerRunId = runId === '*' ? 'wildcard' : runId
        const consumerNonce = globalThis.crypto?.randomUUID?.() ?? Constants.sessionId
        if (!consumerNonce) {
          throw new Error('Secure consumer identity is unavailable')
        }
        const consumerId = `consumer-mobile-${Constants.deviceName || 'unknown'}-${consumerRunId}-${consumerNonce}`

        // Build connection options
        const connectOptions: IClientOptions = {
          clientId: consumerId,
          connectTimeout: 15000,
          reconnectPeriod: 3000,
          keepalive: 30,
          clean: false
        }

        // Add authentication if provided
        if (mqttConfig.username) {
          connectOptions.username = mqttConfig.username
        }
        if (mqttConfig.password) {
          connectOptions.password = mqttConfig.password
        }

        // Handle TLS/SSL options for wss
        if (mqttConfig.protocol === 'wss') {
          connectOptions.rejectUnauthorized = mqttConfig.rejectUnauthorized

          // Add CA certificate if provided
          if (mqttConfig.ca) {
            connectOptions.ca = mqttConfig.ca
          }
        }

        client = mqtt.connect(brokerUrl, connectOptions)

        // Set up error handlers BEFORE anything else to catch early failures
        client.on('error', (err: Error) => {
          // Ignore errors during shutdown - they're expected
          if (isShuttingDown) return
          log(`❌ MQTT error: ${err.message}`)
        })

        // Attach stream error handler
        if (client.stream) {
          client.stream.on('error', (err: Error) => {
            // Ignore errors during shutdown - they're expected
            if (isShuttingDown) return
            log(`❌ WebSocket error: ${err.message}`)
          })
        }

        if (executor.initProfiling) {
          executor.initProfiling()
          log('📈 Profiling enabled')
        }

        if (!testDefinitions) {
          log('⚠️  No test definitions bundled — consumer will fail on queued test resolution')
        }

        // Create consumer using framework's ConsumerBase
        const consumer = new ConsumerBase(
          client,
          consumerId,
          consumerPlatform,
          runId,
          executor,
          {
            log: (message: string) => {
              // Detect shutdown to suppress subsequent errors
              if (message.includes('Consumer shutting down')) {
                isShuttingDown = true
              }
              log(message)
            },
            onBootstrap: bootstrap,
            updateStats: (update: Record<string, unknown>) => {
              updateStats(update as Parameters<typeof updateStats>[0])
            }
          },
          testDefinitions
        )
        const consumerSessionId = consumer.getSessionId()

        consumerRef.current = consumer
        consumer.setupMqttHandlers()

        client.on('offline', () => {
          if (!isShuttingDown) log('📴 Client offline')
        })

        client.on('reconnect', () => {
          if (!isShuttingDown) log('🔄 Reconnecting...')
        })

        // In-app memory poller.
        //
        // Reads the resident-memory counter directly from the app process and
        // publishes over MQTT to the producer's qvac/app-memory topic. On iOS
        // this reads task_vm_info (phys_footprint + resident_size +
        // region_count); on Android it reads the toolkit's
        // PSS number (published as smaps_rollup.pss). The Android /proc worklet
        // below adds VmRSS / USS / mmap-region series. Samples
        // hit the producer immediately, so a hard crash on the device only
        // loses the un-published delta since the last report tick.
        //
        // Caveat: the poller pauses while the JS thread is blocked, so a long
        // synchronous workload won't be sampled until it yields.
        //
        // Two rates:
        //   - measure: how often we read the in-process memory counter
        //   - report:  how often we publish to MQTT (publishes the max over
        //              the report window)
        // Decoupling lets us catch sub-report-interval spikes without flooding
        // MQTT. Defaults: measure 50 ms (20 Hz), report 200 ms (5 Hz).
        // EXPO_PUBLIC_QVAC_APP_MEM_INTERVAL_MS overrides the report rate;
        // EXPO_PUBLIC_QVAC_APP_MEM_MEASURE_MS overrides the measure rate.
        // Setting either to 0 disables that side; report=0 disables in-app
        // entirely.
        const reportIntervalMs = parseInt(
          process.env.EXPO_PUBLIC_QVAC_APP_MEM_INTERVAL_MS || '200',
          10
        )
        const measureIntervalMs = parseInt(
          process.env.EXPO_PUBLIC_QVAC_APP_MEM_MEASURE_MS || '50',
          10
        )
        if (typeof getMemoryUsage === 'function' && reportIntervalMs > 0 && measureIntervalMs > 0) {
          const platformName: 'ios' | 'android' = Platform.OS === 'ios' ? 'ios' : 'android'
          const residentMetric =
            platformName === 'ios' ? 'task_vm_info.physFootprint' : 'smaps_rollup.pss'

          // Per-metric window state. Resets on each report tick.
          let windowMaxByMetric: Record<string, MemoryWindowSample> = {}

          const stopMemoryPoller = () => {
            if (memMeasureHandle) {
              clearInterval(memMeasureHandle)
              memMeasureHandle = undefined
            }
            if (memReportHandle) {
              clearInterval(memReportHandle)
              memReportHandle = undefined
            }
          }

          const updateWindowMax = (metric: string, value: number, unit: MemoryUnit, ts: number) => {
            if (!isPositiveFiniteNumber(value)) return
            const current = windowMaxByMetric[metric]
            if (!current || value > current.value) {
              windowMaxByMetric[metric] = { value, ts, unit }
            }
          }

          const measure = () => {
            // Stop the moment shutdown starts so we don't keep recording
            // a window that will never get published.
            if (isShuttingDown) {
              stopMemoryPoller()
              return
            }
            try {
              const ts = Date.now()
              if (platformName === 'ios' && typeof getIosTaskVmInfo === 'function') {
                const info = getIosTaskVmInfo()
                if (isPositiveFiniteNumber(info.physFootprintMb)) {
                  updateWindowMax(
                    'task_vm_info.physFootprint',
                    info.physFootprintMb * 1024,
                    'kb',
                    ts
                  )
                }
                if (isPositiveFiniteNumber(info.regionCount)) {
                  updateWindowMax('task_vm_info.region_count', info.regionCount, 'count', ts)
                }
                if (isPositiveFiniteNumber(info.residentSizeKb)) {
                  updateWindowMax('task_vm_info.resident_size', info.residentSizeKb, 'kb', ts)
                }
              } else {
                const mb = getMemoryUsage!()
                if (isPositiveFiniteNumber(mb)) {
                  updateWindowMax(residentMetric, mb * 1024, 'kb', ts)
                }
              }
            } catch (err) {
              if (process.env.EXPO_PUBLIC_QVAC_APP_MEM_DEBUG === 'true') {
                log(`mem measure err: ${(err as Error).message}`)
              }
            }
          }

          const report = () => {
            // Once shutdown has started the MQTT client may already be
            // closed — publishing would either silently fail or log a
            // stream error. Stop the timer entirely.
            if (isShuttingDown) {
              stopMemoryPoller()
              return
            }
            const samples = Object.entries(windowMaxByMetric)
            if (samples.length === 0) return // no measurements taken (JS thread was blocked)
            // Reset window before publish so that the next interval starts fresh.
            windowMaxByMetric = {}
            for (const [metric, sample] of samples) {
              try {
                client?.publish(
                  'qvac/app-memory',
                  JSON.stringify({
                    runId,
                    consumerId,
                    sessionId: consumerSessionId,
                    ts: sample.ts,
                    memoryKb: Math.round(sample.value),
                    metric,
                    unit: sample.unit,
                    platform: platformName
                  }),
                  { qos: 0 }
                )
              } catch (err) {
                if (process.env.EXPO_PUBLIC_QVAC_APP_MEM_DEBUG === 'true') {
                  log(`mem publish err: ${(err as Error).message}`)
                }
              }
            }
          }

          memMeasureHandle = setInterval(measure, measureIntervalMs)
          memReportHandle = setInterval(report, reportIntervalMs)

          // Stop the poller only on real teardown (client.end()), not on
          // transient `close` events that fire during normal MQTT reconnect
          // cycles -- otherwise the first transient disconnect would
          // permanently clear both intervals and memory metrics would go
          // silent for the rest of the run. The measure/report callbacks
          // already self-guard via isShuttingDown for the in-flight
          // shutdown race.
          client.on('end', stopMemoryPoller)
          log(
            `📈 In-app memory poller started (measure ${measureIntervalMs}ms, report ${reportIntervalMs}ms, window-max)`
          )
        }

        // Android /proc memory sampler.
        //
        // A dedicated Bare worklet (proc-mem-worklet.mjs) reads /proc/self/maps
        // (mmap region count), /proc/self/status (VmRSS), /proc/self/smaps_rollup
        // (USS) and the one-time /proc/sys/vm/max_map_count ceiling, then pushes batches over
        // bare-rpc. We republish each value on qvac/app-memory as its own
        // metric label so the report renders a chart + per-test delta per
        // series. iOS has no /proc, so this is Android-only; the in-app poller
        // above reads task_vm_info for the iOS equivalents.
        const procMemIntervalMs = parseInt(
          process.env.EXPO_PUBLIC_QVAC_PROC_MEM_INTERVAL_MS || '500',
          10
        )
        if (
          Platform.OS === 'android' &&
          procMemIntervalMs > 0 &&
          Worklet &&
          BareRPC &&
          procMemBundle
        ) {
          try {
            procMemWorklet = new Worklet()
            procMemWorklet.start('/proc-mem-worklet.bundle', procMemBundle, [
              String(procMemIntervalMs)
            ])

            // eslint-disable-next-line no-new
            new BareRPC(procMemWorklet.IPC, (req: any) => {
              if (req.command !== RPC_MEM_SAMPLE) return
              if (isShuttingDown) return
              let samples: any[]
              try {
                samples = JSON.parse(decodeRpcData(req.data))
              } catch {
                return
              }
              if (!Array.isArray(samples)) return
              for (const s of samples) {
                if (!s || typeof s.value !== 'number' || typeof s.metric !== 'string') continue
                try {
                  client?.publish(
                    'qvac/app-memory',
                    JSON.stringify({
                      runId,
                      consumerId,
                      sessionId: consumerSessionId,
                      ts: typeof s.ts === 'number' ? s.ts : Date.now(),
                      memoryKb: s.value,
                      metric: s.metric,
                      unit: s.unit === 'count' ? 'count' : 'kb',
                      limitKb: typeof s.limit === 'number' ? s.limit : null,
                      platform: 'android'
                    }),
                    { qos: 0 }
                  )
                } catch (err) {
                  if (process.env.EXPO_PUBLIC_QVAC_APP_MEM_DEBUG === 'true') {
                    log(`proc-mem publish err: ${(err as Error).message}`)
                  }
                }
              }
            })

            client.on('end', stopProcMemWorklet)
            log(`📈 /proc memory sampler started (interval ${procMemIntervalMs}ms)`)
          } catch (err) {
            stopProcMemWorklet()
            log(`⚠️  /proc memory sampler unavailable: ${(err as Error).message}`)
          }
        }
      } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : String(error)
        log(`❌ Fatal error: ${errorMessage}`)
        console.error(error)
      }
    })()

    return () => {
      isShuttingDown = true
      if (memMeasureHandle) {
        clearInterval(memMeasureHandle)
        memMeasureHandle = undefined
      }
      if (memReportHandle) {
        clearInterval(memReportHandle)
        memReportHandle = undefined
      }
      stopProcMemWorklet()
      if (consumerRef.current) {
        // forceShutdown() owns MQTT teardown (it awaits a checkpoint publish then
        // ends the client). Don't call client.end() here or we'd abort that
        // in-flight publish. Cleanup can't be async, so fire-and-forget and
        // swallow rejections to avoid an unhandled promise rejection.
        consumerRef.current.forceShutdown().catch(() => {})
      } else if (client) {
        // Fallback teardown only when there is no consumer to own it.
        client.end()
      }
    }
  }, [])

  return null // This is a headless component
}
