// Auto-generated by generate-assets.cjs - DO NOT EDIT MANUALLY
// Run: node shared-test-data/generate-assets.cjs

export const audio = {
	"10min-mp3-320kbps.mp3": require("./audio/10min-mp3-320kbps.mp3"),
	"5min-mp3-128kbps.mp3": require("./audio/5min-mp3-128kbps.mp3"),
	"classical_symphony.mp3": require("./audio/classical_symphony.mp3"),
	"classical_symphony_corrupted.mp3": require("./audio/classical_symphony_corrupted.mp3"),
	"corrupted.mp3": require("./audio/corrupted.mp3"),
	"corrupted.wav": require("./audio/corrupted.wav"),
	"ocean_waves_ambient.wav": require("./audio/ocean_waves_ambient.wav"),
	"only-music.mp3": require("./audio/only-music.mp3"),
	"silence.m4a": require("./audio/silence.m4a"),
	"transcription-short.aac": require("./audio/transcription-short.aac"),
	"transcription-short.m4a": require("./audio/transcription-short.m4a"),
	"transcription-short.mp3": require("./audio/transcription-short.mp3"),
	"transcription-short.ogg": require("./audio/transcription-short.ogg"),
	"transcription-short.wav": require("./audio/transcription-short.wav"),
	"transcription-short.wma": require("./audio/transcription-short.wma"),
};

export const documents = {
	"desert_adventure_large.txt": require("./documents/desert_adventure_large.txt"),
	"mountain_hiking_guide.txt": require("./documents/mountain_hiking_guide.txt"),
	"ocean_waves_poem.txt": require("./documents/ocean_waves_poem.txt"),
	"sunset_beach_corrupted.txt": require("./documents/sunset_beach_corrupted.txt"),
};

export const code = {
	"api_response.json": require("./code/api_response.json"),
	"data_analysis.py": require("./code/data_analysis.py"),
	"interactive_gallery.js": require("./code/interactive_gallery.js"),
	"portfolio_website.html": require("./code/portfolio_website.html"),
};

export const images = {
	"after.jpg": require("./images/after.jpg"),
	"arabic-document.jpg": require("./images/arabic-document.jpg"),
	"base64-test.png": require("./images/base64-test.png"),
	"before.jpg": require("./images/before.jpg"),
	"cat.jpg": require("./images/cat.jpg"),
	"chart.jpg": require("./images/chart.jpg"),
	"chinese-menu.jpg": require("./images/chinese-menu.jpg"),
	"context-image.jpg": require("./images/context-image.jpg"),
	"hindi-poster.jpg": require("./images/hindi-poster.jpg"),
	"japanese-sign.jpg": require("./images/japanese-sign.jpg"),
	"large-4k.jpg": require("./images/large-4k.jpg"),
	"logo.png": require("./images/logo.png"),
	"low-quality.jpg": require("./images/low-quality.jpg"),
	"mixed-language-store.jpg": require("./images/mixed-language-store.jpg"),
	"objects.jpg": require("./images/objects.jpg"),
	"ocr-blurry-text.png": require("./images/ocr-blurry-text.png"),
	"ocr-horizontally-inverted.png": require("./images/ocr-horizontally-inverted.png"),
	"ocr-misaligned-text.png": require("./images/ocr-misaligned-text.png"),
	"ocr-multi-sized-text.png": require("./images/ocr-multi-sized-text.png"),
	"ocr-multiple-fonts.png": require("./images/ocr-multiple-fonts.png"),
	"ocr-simple-test.jpg": require("./images/ocr-simple-test.jpg"),
	"ocr-simple-test.png": require("./images/ocr-simple-test.png"),
	"ocr-single-language.png": require("./images/ocr-single-language.png"),
	"ocr-vertically-inverted.png": require("./images/ocr-vertically-inverted.png"),
	"photo.png": require("./images/photo.png"),
	"photo.webp": require("./images/photo.webp"),
	"room.jpg": require("./images/room.jpg"),
	"russian-document.jpg": require("./images/russian-document.jpg"),
	"scene.jpg": require("./images/scene.jpg"),
	"sign.jpg": require("./images/sign.jpg"),
	"small-64.jpg": require("./images/small-64.jpg"),
	"sunset.jpg": require("./images/sunset.jpg"),
};
