// Auto-generated by generate-assets.cjs - DO NOT EDIT MANUALLY
// Run: node shared-test-data/generate-assets.cjs

export const audio = {
	"10min-mp3-320kbps.mp3": require("./audio/10min-mp3-320kbps.mp3"),
	"5min-mp3-128kbps.mp3": require("./audio/5min-mp3-128kbps.mp3"),
	"classical_symphony.mp3": require("./audio/classical_symphony.mp3"),
	"classical_symphony_corrupted.mp3": require("./audio/classical_symphony_corrupted.mp3"),
	"corrupted.mp3": require("./audio/corrupted.mp3"),
	"corrupted.wav": require("./audio/corrupted.wav"),
	"ocean_waves_ambient.wav": require("./audio/ocean_waves_ambient.wav"),
	"only-music.mp3": require("./audio/only-music.mp3"),
	"silence.m4a": require("./audio/silence.m4a"),
	"transcription-short.aac": require("./audio/transcription-short.aac"),
	"transcription-short.m4a": require("./audio/transcription-short.m4a"),
	"transcription-short.mp3": require("./audio/transcription-short.mp3"),
	"transcription-short.ogg": require("./audio/transcription-short.ogg"),
	"transcription-short.wav": require("./audio/transcription-short.wav"),
	"transcription-short.wma": require("./audio/transcription-short.wma"),
};

export const documents = {
	"desert_adventure_large.txt": require("./documents/desert_adventure_large.txt"),
	"mountain_hiking_guide.txt": require("./documents/mountain_hiking_guide.txt"),
	"ocean_waves_poem.txt": require("./documents/ocean_waves_poem.txt"),
	"sunset_beach_corrupted.txt": require("./documents/sunset_beach_corrupted.txt"),
};

export const code = {
	"api_response.json": require("./code/api_response.json"),
	"data_analysis.py": require("./code/data_analysis.py"),
	"interactive_gallery.js": require("./code/interactive_gallery.js"),
	"portfolio_website.html": require("./code/portfolio_website.html"),
};
