#!/usr/bin/env node

/**
 * Generates assets.js manifest by scanning directories
 * Run this when adding/removing files: node generate-assets.cjs
 */

const fs = require('fs');
const path = require('path');

const ASSET_DIRS = {
	audio: ['wav', 'mp3', 'm4a', 'aac', 'ogg', 'wma'],
	documents: ['txt'],
	code: ['py', 'js', 'json', 'html'],
	images: ['jpg', 'jpeg', 'png', 'bmp', 'webp'],
};

function scanDir(dir, extensions) {
	const dirPath = path.join(__dirname, dir);
	if (!fs.existsSync(dirPath)) return [];
	
	return fs.readdirSync(dirPath)
		.filter(f => extensions.some(ext => f.endsWith(`.${ext}`)))
		.sort();
}

function generateManifest() {
	let output = `// Auto-generated by generate-assets.cjs - DO NOT EDIT MANUALLY
// Run: node shared-test-data/generate-assets.cjs

`;

	for (const [category, extensions] of Object.entries(ASSET_DIRS)) {
		const files = scanDir(category, extensions);
		
		output += `export const ${category} = {\n`;
		for (const file of files) {
			output += `\t"${file}": require("./${category}/${file}"),\n`;
		}
		output += `};\n\n`;
	}

	const outPath = path.join(__dirname, 'assets.js');
	fs.writeFileSync(outPath, output.trimEnd() + '\n');
	console.log(`Generated ${outPath} with ${Object.values(ASSET_DIRS).flat().length} asset types`);
}

generateManifest();

