/**
 * eSpeak-ng-data utilities for mobile
 *
 * Handles copying espeak-ng-data from app assets to the filesystem
 * and provides the correct path for the TTS model loader.
 *
 * IMPORTANT: On Android, the native TTS addon CANNOT read from APK asset paths
 * (e.g. /android_asset/...). The data MUST be copied to the app's document/files
 * directory, and the path must NOT have a "file://" prefix.
 *
 * See: Slack thread on TTS crash (SIGABRT / pthread_mutex_lock on destroyed mutex)
 */

import {
	documentDirectory,
	bundleDirectory,
	getInfoAsync,
	makeDirectoryAsync,
	copyAsync,
	readAsStringAsync,
} from "expo-file-system/legacy";
import { Platform } from "react-native";
import { env } from "./env";

// Target directory name for espeak-ng-data in the app's files directory
const ESPEAK_DATA_DIR_NAME = "espeak-ng-data";

/**
 * Get the filesystem path where espeak-ng-data will be stored
 * This is always the document directory (real filesystem, not APK assets)
 */
export function getEspeakDataPath(): string {
	return `${documentDirectory}${ESPEAK_DATA_DIR_NAME}`;
}

/**
 * Check if espeak-ng-data has been fully copied to the files directory
 */
export async function isEspeakDataInitialized(): Promise<boolean> {
	const targetDir = getEspeakDataPath();
	try {
		const info = await getInfoAsync(targetDir);
		if (!info.exists) {
			return false;
		}

		// Check for phondata - a critical espeak-ng file
		const phondataInfo = await getInfoAsync(`${targetDir}/phondata`);
		return phondataInfo.exists;
	} catch (error) {
		console.log("[espeak-utils] Error checking espeak data:", error);
		return false;
	}
}

/**
 * Get the platform-specific source URI for espeak-ng-data bundled assets.
 *
 * Android: assets are in APK, accessible via asset:// URI
 * iOS: assets are in the app bundle, accessible via bundleDirectory
 */
function getBundledAssetBaseUri(): string {
	if (Platform.OS === "android") {
		return "asset:///espeak-ng-data";
	}
	// iOS: bundleDirectory gives the app bundle path (e.g. file:///var/.../Bundle/)
	return `${bundleDirectory}espeak-ng-data`;
}

/**
 * Copy espeak-ng-data from bundled assets to the app's files directory.
 *
 * Uses the _manifest.json generated by the withEspeakNgData Expo plugin
 * to know which files need to be copied.
 *
 * Works on both Android (APK assets) and iOS (app bundle).
 */
async function copyBundledAssetsToFilesDir(
	log: (msg: string) => void
): Promise<boolean> {
	const targetDir = getEspeakDataPath();
	const baseUri = getBundledAssetBaseUri();

	try {
		// Try to read the manifest generated by the build plugin
		const manifestUri = `${baseUri}/_manifest.json`;
		let fileList: string[];

		try {
			const manifestContent = await readAsStringAsync(manifestUri);
			fileList = JSON.parse(manifestContent);
			log(`[espeak-utils] Manifest loaded: ${fileList.length} files to copy`);
		} catch {
			log("[espeak-utils] No manifest found");
			throw new Error(
				"Manifest not found - please rebuild with updated withEspeakNgData plugin"
			);
		}

		// Collect unique directories that need to be created
		const dirs = new Set<string>();
		for (const file of fileList) {
			const parts = file.split("/");
			if (parts.length > 1) {
				for (let i = 1; i < parts.length; i++) {
					dirs.add(parts.slice(0, i).join("/"));
				}
			}
		}

		// Create target directory structure
		await makeDirectoryAsync(targetDir, { intermediates: true });
		for (const dir of Array.from(dirs).sort()) {
			await makeDirectoryAsync(`${targetDir}/${dir}`, {
				intermediates: true,
			});
		}
		log(`[espeak-utils] Created ${dirs.size} directories`);

		// Copy files from bundled assets to files directory
		let copied = 0;
		let errors = 0;
		for (const file of fileList) {
			if (file === "_manifest.json") continue;

			const src = `${baseUri}/${file}`;
			const dest = `${targetDir}/${file}`;

			try {
				await copyAsync({ from: src, to: dest });
				copied++;
			} catch (err: any) {
				if (errors < 5) {
					log(`[espeak-utils] Failed to copy ${file}: ${err.message}`);
				}
				errors++;
			}
		}

		log(
			`[espeak-utils] Copied ${copied}/${fileList.length} files${errors > 0 ? ` (${errors} errors)` : ""}`
		);
		return copied > 0;
	} catch (error: any) {
		log(`[espeak-utils] Asset copy failed: ${error.message}`);
		return false;
	}
}

/**
 * Initialize espeak-ng-data by copying from app assets to filesystem.
 *
 * On Android, files bundled in APK assets are NOT accessible via file paths
 * by native code. They must be copied to the app's document directory first.
 *
 * Returns true if initialization was successful, false otherwise.
 */
export async function initializeEspeakData(
	onProgress?: (message: string) => void
): Promise<boolean> {
	const log = onProgress || console.log;

	try {
		// Check if already initialized
		if (await isEspeakDataInitialized()) {
			log("[espeak-utils] espeak-ng-data already initialized");
			return true;
		}

		const targetDir = getEspeakDataPath();
		log(`[espeak-utils] Initializing espeak-ng-data to ${targetDir}`);

		if (Platform.OS === "android" || Platform.OS === "ios") {
			// Both platforms: copy bundled assets to the files directory
			// Android: native code cannot read from APK asset paths
			// iOS: bundle is read-only; copy to files dir for consistent writable access
			const success = await copyBundledAssetsToFilesDir(log);
			if (!success) {
				log("[espeak-utils] WARNING: Failed to copy espeak-ng-data from bundled assets");
				return false;
			}
			return true;
		}

		return false;
	} catch (error: any) {
		log(`[espeak-utils] Error initializing espeak data: ${error.message}`);
		return false;
	}
}

/**
 * Get the appropriate espeak data path for the SDK.
 *
 * CRITICAL: The path must be a real filesystem path (NOT asset://, NOT file://)
 * - Android native code cannot read from APK asset paths
 * - The file:// prefix must be stripped
 *
 * Priority:
 * 1. EXPO_PUBLIC_ESPEAK_DATA_PATH env variable (if set)
 * 2. App document directory path (files dir, no file:// prefix)
 */
export function getEspeakDataPathForSDK(): string {
	// Check for environment variable override
	if (env.EXPO_PUBLIC_ESPEAK_DATA_PATH) {
		let path = env.EXPO_PUBLIC_ESPEAK_DATA_PATH;
		// Strip file:// prefix if present
		if (path.startsWith("file://")) {
			path = path.substring(7);
		}
		console.log(`[espeak-utils] Using env override: ${path}`);
		return path;
	}

	// Use the files directory path - strip file:// prefix
	let path = getEspeakDataPath();
	if (path.startsWith("file://")) {
		path = path.substring(7);
	}

	return path;
}
